# Generated by Django 3.0.4 on 2020-03-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20200327_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
