# Generated by Django 3.0.4 on 2020-03-27 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200328_0034'),
        ('carts', '0007_auto_20200328_0114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartItem',
        ),
    ]
