# Generated by Django 3.0.4 on 2020-05-02 09:39

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_auto_20200328_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_adress', models.CharField(max_length=100)),
                ('apartment_adress', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zip_code', models.CharField(max_length=100)),
                ('adress_type', models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1)),
            ],
        ),
    ]
