# Generated by Django 3.0.4 on 2020-05-02 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0011_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='billing_adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_adress', to='carts.Adress'),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_adress', to='carts.Adress'),
        ),
    ]
