# Generated by Django 3.0.4 on 2020-05-02 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0014_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carts.Customer'),
        ),
    ]
