# Generated by Django 3.0.4 on 2020-05-02 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0009_add_subregion'),
        ('carts', '0016_auto_20200502_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='city',
        ),
        migrations.AddField(
            model_name='adress',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
        ),
    ]
