# Generated by Django 3.0.4 on 2020-05-02 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0019_auto_20200502_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='shipping',
            new_name='ordered',
        ),
    ]
