# Generated by Django 3.0.4 on 2020-05-03 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0020_auto_20200502_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adress',
            options={'verbose_name_plural': 'Adresses'},
        ),
    ]
