# Generated by Django 3.0.4 on 2020-03-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_prdocutimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrdocutImage',
            new_name='ProductImage',
        ),
    ]
