# Generated by Django 3.0.4 on 2020-05-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200503_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/placeholder.png', upload_to='products/images'),
        ),
    ]
